apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: the-listener
spec:
  triggers:
    - binding:
        name: theTriggerBinding
      template:
        name: theTemplateTrigger
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: xx1
      taskRef:
        name: the-task
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: the-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "02 lab2"
    - name: lslslash
      image: ubuntu
      command:
        - ls
      args:
        - "-l"
        - "/"
    - name: lsl-ubuntu
      image: ubuntu
      command:
        - ls
      args:
        - "-l"
    - name: pwd
      image: ubuntu
      command:
        - pwd
    - name: ls
      image: ubuntu
      command:
        - ls
    - name: env
      image: ubuntu
      command:
        - env
    - name: write
      image: ubuntu
      command:
        - "/bin/bash"
      args:
        - "-c"
        - "echo stuff > file; ls; cat file"
    - name: lsafter
      image: ubuntu
      command:
        - ls
      args:
        - "-l"
    - name: catafter
      image: ubuntu
      command:
        - cat
      args:
        - file

